# Generated by Django 2.2.16 on 2020-09-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('member_type', models.CharField(max_length=30)),
                ('gender', models.BooleanField()),
                ('birthdate', models.DateField()),
                ('nickname', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_from', to='ootdApp.Member')),
                ('like_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_to', to='ootdApp.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_image', models.ImageField(upload_to='')),
                ('f_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ootdApp.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_content', models.CharField(max_length=256)),
                ('c_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ootdApp.Feedback')),
                ('c_writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ootdApp.Member')),
            ],
        ),
    ]
