# Generated by Django 3.1.1 on 2020-09-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ootdApp.member')),
                ('f_content', models.TextField()),
                ('f_image', models.ImageField(upload_to='')),
                ('f_category', models.CharField(choices=[('A', 'All'), ('O', 'Outer'), ('T', 'Top'), ('B', 'Bottom'), ('S', 'Shoes'), ('Ac', 'Acc'), ('S', 'Similar')], max_length=2)),
                ('f_comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ootdApp.member')),
                ('f_content', models.TextField()),
                ('m_image', models.ImageField(upload_to='')),
                ('m_category', models.CharField(choices=[('A', 'All'), ('O', 'Outer'), ('T', 'Top'), ('B', 'Bottom'), ('S', 'Shoes'), ('Ac', 'Acc'), ('S', 'Similar')], max_length=2)),
                ('m_comment', models.TextField(null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('follower', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('like', 'follower')},
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('m_type', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('follower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Member_follower', to='ootdApp.member_info')),
                ('like', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Member_like', to='ootdApp.member_info')),
            ],
        ),
    ]
